### ISSUE TITLE
开放的REST API建议使用什么工具UT，WisdomTool REST Client？Postman or 别的？

### ISSUE THREAD

**Issue by wangyudongdom** [Wechat-Group/weixin-java-tools#385]
了解了一下[ WisdomTool REST Client](https://github.com/wisdomtool/rest-client) 工具可以自动化测试RESTful API，是不是可以用在测试微信开放接口上？想着尝试一下。

**Comment by binarywang** [comment]
不明白你在说什么，跟我们这个微信sdk有关系吗？

**Comment by wangyudongdom** [comment]
微信SDK会调后台的API，想试着测试这些RESTful API，不知道你们是使用什么工具测试。
我自己查找一些工具看看，谢谢您的答复！

**Comment by binarywang** [comment]
有很多，postman、restclient等属于浏览器插件的，还有独立的程序如soapui等
