### ISSUE TITLE
sdk集成到项目里面启动报错，注入有问题

### ISSUE THREAD

**Issue by windawaken** [Wechat-Group/weixin-java-tools#482]
错误日志 

WARN AnnotationConfigEmbeddedWebApplicationContext:550 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'loginController': Unsatisfied dependency expressed through field 'loginManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'loginManagerImpl': Unsatisfied dependency expressed through field 'wxService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'cn.binarywang.wx.miniapp.api.WxMaService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2018-03-07 16:56:20,255  INFO DruidDataSource:1375 - {dataSource-1} closed
[2018-03-07 16:56:20.257] - 5191 信息 [restartedMain] --- org.apache.catalina.core.StandardService: Stopping service Tomcat
2018-03-07 16:56:20,272  INFO AutoConfigurationReportLoggingInitializer:101 - 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-03-07 16:56:20,405 ERROR LoggingFailureAnalysisReporter:42 - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field wxService in com.gs.login.manager.impl.LoginManagerImpl required a bean of type 'cn.binarywang.wx.miniapp.api.WxMaService' that could not be found.

Action:

Consider defining a bean of type 'cn.binarywang.wx.miniapp.api.WxMaService' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:60731', transport: 'socket'

Process finished with exit code 0

**Comment by ftong2010** [comment]
weixin-java-tool没有做spring的autoConfiguration，要自己定义WxMaService然后通过@Bean或者XML注册进去
