### ISSUE TITLE
操作微信菜单工具类没有给上层返回微信的报文

### ISSUE THREAD

**Issue by pig4cloud** [Wechat-Group/weixin-java-tools#662]
作者老铁，WxMpMenuServiceImpl 这个 微信返回的报文 都没有返回给上层调用者呀
![image](https://user-images.githubusercontent.com/12409311/42267726-68bbdb8a-7fac-11e8-9b77-371ec47b1a7e.png)

**Comment by binarywang** [comment]
你是说result的值吗？自定义菜单如果创建失败会抛异常，个性化菜单会返回menuId。
你实际跑过代码了？

**Comment by pig4cloud** [comment]
![image](https://user-images.githubusercontent.com/12409311/42269226-3133f7ca-7fb0-11e8-9ebc-7655b176dc28.png)
![image](https://user-images.githubusercontent.com/12409311/42269238-3bc27d38-7fb0-11e8-97d2-1392eaf975ae.png)

**Comment by pig4cloud** [comment]
![image](https://user-images.githubusercontent.com/12409311/42269466-c96a38a6-7fb0-11e8-9561-d2e2caa92c0b.png)
这个只是抛出来的异常

**Comment by binarywang** [comment]
异常里不是有具体错误信息吗？

成功返回的内容你觉得有用吗？

**Comment by pig4cloud** [comment]
OK  尊重你的看法
无非就是 把那个 null 给改成 result  而已

**Comment by binarywang** [comment]
改不改其实没有多大意义，给你返回微信那个原始的result其实也没用。

**Comment by pig4cloud** [comment]
嗯 。非常感谢 感谢作者指导 。如果需要  可以PR一下

**Comment by binarywang** [comment]
好吧，你要保存原始报文的话，确实就不太好兼顾了，毕竟如果是个性化菜单，是要返回menuId的，你如果还同时要原始报文的话，一个返回值也不够的，除非把微信返回值给你，你自己解析，但这样对大部分开发者来说就不够友好了。

**Comment by pig4cloud** [comment]
OK 感谢。问题 close啦
